language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.5
  - 7.0
  - 7.1
  - 7.2

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*
  - SYMFONY_VERSION=3.1.*
  - SYMFONY_VERSION=3.2.*
  - SYMFONY_VERSION=3.3.*
  - SYMFONY_VERSION=3.4.*
  - SYMFONY_VERSION=4.0.*
  - SYMFONY_VERSION=4.1.*
  - SYMFONY_VERSION=4.2.*

matrix:
  fast_finish: true
  exclude:
    - php: 5.5
      env: SYMFONY_VERSION=4.0.*
    - php: 7.0
      env: SYMFONY_VERSION=4.0.*
    - php: 5.5
      env: SYMFONY_VERSION=4.1.*
    - php: 7.0
      env: SYMFONY_VERSION=4.1.*
    - php: 5.5
      env: SYMFONY_VERSION=4.2.*
    - php: 7.0
      env: SYMFONY_VERSION=4.2.*
  include:
    - php: 7.1
      env: SYMFONY_VERSION=4.3.* STABILITY=dev
    - php: 7.2
      env: SYMFONY_VERSION=4.3.* STABILITY=dev
  allow_failures:
    - php: 7.1
      env: SYMFONY_VERSION=4.3.* STABILITY=dev
    - php: 7.2
      env: SYMFONY_VERSION=4.3.* STABILITY=dev

before_install:
  - composer self-update
  - if [ $STABILITY ]; then composer config minimum-stability ${STABILITY}; fi;
  - composer require --dev symfony/framework-bundle:${SYMFONY_VERSION} --no-update

install:
  - composer update --ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress

script:
  - phpunit --coverage-text
